"""Fully resolved compiler-generated HOP plans."""

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import Field, field_validator, model_validator

from hop_design.models.base import HopModel
from hop_design.models.coordinates import Span
from hop_design.models.processing import PlanProcessingRoute
from hop_design.models.references import ReferenceId
from hop_design.models.sequence import (
    EXACT_DNA_ALPHABET,
    SequenceValidationError,
    normalize_dna_sequence,
    reverse_complement_iupac,
)


class FeatureRole(StrEnum):
    """Stable molecular roles in the generic final insert."""

    BASAL_LEFT_ARM = "basal_left_arm"
    PAYLOAD = "payload"
    FOLDBACK_JUNCTION = "foldback_junction"
    PAIRED_PAYLOAD = "paired_payload"
    BASAL_RIGHT_ARM = "basal_right_arm"


class SequenceRecord(HopModel):
    """A named exact or symbolic DNA sequence generated by the compiler."""

    record_id: str = Field(min_length=1)
    sequence: str

    @field_validator("sequence", mode="before")
    @classmethod
    def normalize_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)

    @property
    def is_symbolic(self) -> bool:
        """Return whether this sequence still contains IUPAC ambiguity symbols."""
        return not set(self.sequence) <= EXACT_DNA_ALPHABET


class SequenceFeature(HopModel):
    """A sequence-bearing feature located on the final insert."""

    role: FeatureRole
    span: Span
    sequence: str

    @field_validator("sequence", mode="before")
    @classmethod
    def normalize_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)


class CompilationLock(HopModel):
    """Versions and resolved public references needed to replay a plan."""

    compiler_distribution: Literal["hop-design"] = "hop-design"
    compiler_version: str = Field(min_length=1)
    defaults_ref: ReferenceId
    catalog_ref: ReferenceId
    constraint_profile_ref: ReferenceId
    processing_route_ref: ReferenceId
    foldback_junction_ref: ReferenceId
    basal_junction_ref: ReferenceId


class HopPlan(HopModel):
    """An immutable, fully resolved physical build plan."""

    schema_id: Literal["hop.plan/v1"] = Field(default="hop.plan/v1", alias="schema")
    plan_id: ReferenceId
    design_id: str = Field(pattern=r"^[a-z0-9][a-z0-9._-]{0,63}$")
    spec_digest: str = Field(pattern=r"^sha256:[0-9a-f]{64}$")
    payload_sequence: str
    paired_payload_sequence: str
    source_oligo: SequenceRecord
    final_insert: SequenceRecord
    features: tuple[SequenceFeature, ...] = Field(min_length=1)
    processing_route: PlanProcessingRoute
    lock: CompilationLock

    @field_validator("payload_sequence", "paired_payload_sequence", mode="before")
    @classmethod
    def normalize_payload_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)

    @model_validator(mode="after")
    def validate_derivations(self) -> HopPlan:
        if self.paired_payload_sequence != reverse_complement_iupac(self.payload_sequence):
            raise ValueError("Paired payload sequence must be derived from the authored payload.")
        if self.processing_route.route_id != self.lock.processing_route_ref:
            raise ValueError("Resolved processing route and lock record disagree.")

        expected_roles = tuple(FeatureRole)
        actual_roles = tuple(feature.role for feature in self.features)
        if self.processing_route.kind == "direct_synthesis":
            if self.source_oligo.sequence != self.final_insert.sequence:
                raise ValueError(
                    "The direct-synthesis route requires source oligo and final insert equality."
                )
            if actual_roles != expected_roles:
                raise ValueError("Final-insert features must use the declared generic-route order.")
            foldback_sequence = self.processing_route.foldback_junction.sequence
            basal_left_arm = self.processing_route.basal_junction.left_arm
            basal_right_arm = self.processing_route.basal_junction.right_arm
            foldback_ref = self.processing_route.foldback_junction.junction_id
            basal_ref = self.processing_route.basal_junction.junction_id
        else:
            expected_source = (
                self.processing_route.foldback.precursor_sequence
                if self.processing_route.released_state is None
                else self.processing_route.released_state.precursor_top_strand
            )
            if self.source_oligo.sequence != expected_source:
                raise ValueError("Resolved-event source oligo must equal the actual route input.")
            if actual_roles != expected_roles:
                raise ValueError(
                    "Resolved-event final-insert features must contain each physical role once "
                    "in the declared assembly order."
                )
            foldback_sequence = self.processing_route.foldback.junction.sequence
            basal_left_arm = self.processing_route.basal.junction.left_arm
            basal_right_arm = self.processing_route.basal.junction.right_arm
            foldback_ref = self.processing_route.foldback.junction.junction_id
            basal_ref = self.processing_route.basal.junction.junction_id
        if self.processing_route.catalog_ref != self.lock.catalog_ref:
            raise ValueError("Resolved catalog and lock record disagree.")
        if foldback_ref != self.lock.foldback_junction_ref:
            raise ValueError("Resolved foldback and lock record disagree.")
        if basal_ref != self.lock.basal_junction_ref:
            raise ValueError("Resolved basal and lock record disagree.")
        cursor = 0
        pieces: list[str] = []
        for feature in self.features:
            if feature.span.start.offset != cursor:
                raise ValueError("Final-insert feature spans must be contiguous and ordered.")
            if feature.span.length.value != len(feature.sequence):
                raise ValueError("Final-insert feature span length must equal its sequence length.")
            cursor = feature.span.end.offset
            pieces.append(feature.sequence)
        if (
            cursor != len(self.final_insert.sequence)
            or "".join(pieces) != self.final_insert.sequence
        ):
            raise ValueError(
                "Final-insert features must partition and reconstruct the final sequence."
            )
        feature_by_role = {feature.role: feature for feature in self.features}
        if feature_by_role[FeatureRole.PAYLOAD].sequence != self.payload_sequence:
            raise ValueError("Payload feature must equal the authored payload sequence.")
        if feature_by_role[FeatureRole.PAIRED_PAYLOAD].sequence != self.paired_payload_sequence:
            raise ValueError("Paired-payload feature must equal the derived paired sequence.")
        if feature_by_role[FeatureRole.FOLDBACK_JUNCTION].sequence != foldback_sequence:
            raise ValueError("Foldback-junction feature must equal the resolved foldback junction.")
        if feature_by_role[FeatureRole.BASAL_LEFT_ARM].sequence != basal_left_arm:
            raise ValueError("Basal-left feature must equal the resolved basal junction.")
        if feature_by_role[FeatureRole.BASAL_RIGHT_ARM].sequence != basal_right_arm:
            raise ValueError("Basal-right feature must equal the resolved basal junction.")
        return self
