"""Fully resolved compiler-generated HOP plans."""

from __future__ import annotations

import hashlib
from enum import StrEnum
from typing import Literal

from pydantic import Field, field_validator, model_validator

from hop_design.models.base import HopModel
from hop_design.models.coordinates import Span
from hop_design.models.processing import PlanProcessingRoute
from hop_design.models.references import ReferenceId
from hop_design.models.sequence import (
    EXACT_DNA_ALPHABET,
    SequenceValidationError,
    normalize_dna_sequence,
    reverse_complement_iupac,
)


class FeatureRole(StrEnum):
    """Stable molecular roles in the compiled hairpin encoding."""

    BASAL_LEFT_ARM = "basal_left_arm"
    STEM_EXTENSION_LEFT_ARM = "stem_extension_left_arm"
    PAYLOAD = "payload"
    FOLDBACK_JUNCTION = "foldback_junction"
    PAIRED_PAYLOAD = "paired_payload"
    STEM_EXTENSION_RIGHT_ARM = "stem_extension_right_arm"
    BASAL_RIGHT_ARM = "basal_right_arm"


class SequenceRecord(HopModel):
    """A named exact or symbolic DNA sequence generated by the compiler."""

    record_id: str = Field(min_length=1)
    sequence: str

    @field_validator("sequence", mode="before")
    @classmethod
    def normalize_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)

    @property
    def is_symbolic(self) -> bool:
        """Return whether this sequence still contains IUPAC ambiguity symbols."""
        return not set(self.sequence) <= EXACT_DNA_ALPHABET


class SequenceFeature(HopModel):
    """A sequence-bearing feature located on a compiled encoding."""

    role: FeatureRole
    span: Span
    sequence: str

    @field_validator("sequence", mode="before")
    @classmethod
    def normalize_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)


class HairpinEncodingInsert(HopModel):
    """The one-dimensional sequence and features that encode one hairpin core."""

    kind: Literal["hairpin_encoding_insert"] = "hairpin_encoding_insert"
    representation: Literal["one_dimensional_sequence"] = "one_dimensional_sequence"
    alphabet: Literal["dna"] = "dna"
    coordinate_system: Literal["zero_based_half_open"] = "zero_based_half_open"
    record_id: str = Field(min_length=1)
    sequence: str
    sequence_digest: str = Field(pattern=r"^sha256:[0-9a-f]{64}$")
    features: tuple[SequenceFeature, ...] = Field(min_length=1)

    @field_validator("sequence", mode="before")
    @classmethod
    def normalize_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)

    @property
    def is_symbolic(self) -> bool:
        """Return whether the encoding contains IUPAC ambiguity symbols."""
        return not set(self.sequence) <= EXACT_DNA_ALPHABET

    @model_validator(mode="after")
    def validate_encoding(self) -> HairpinEncodingInsert:
        observed_digest = f"sha256:{hashlib.sha256(self.sequence.encode()).hexdigest()}"
        if self.sequence_digest != observed_digest:
            raise ValueError("Hairpin-encoding digest must match its sequence.")
        cursor = 0
        pieces: list[str] = []
        for feature in self.features:
            if feature.span.start.offset != cursor:
                raise ValueError("Hairpin-encoding feature spans must be contiguous and ordered.")
            if feature.span.length.value != len(feature.sequence):
                raise ValueError(
                    "Hairpin-encoding feature span length must equal its sequence length."
                )
            cursor = feature.span.end.offset
            pieces.append(feature.sequence)
        if cursor != len(self.sequence) or "".join(pieces) != self.sequence:
            raise ValueError(
                "Hairpin-encoding features must partition and reconstruct the encoded sequence."
            )
        return self


class CompilationLock(HopModel):
    """Versions and resolved public references needed to replay a plan."""

    compiler_distribution: Literal["hop-design"] = "hop-design"
    compiler_version: str = Field(min_length=1)
    defaults_ref: ReferenceId
    catalog_ref: ReferenceId
    constraint_profile_ref: ReferenceId
    processing_route_ref: ReferenceId
    foldback_junction_ref: ReferenceId
    basal_junction_ref: ReferenceId


class HopPlan(HopModel):
    """An immutable, fully resolved physical build plan."""

    schema_id: Literal["hop.plan/v2"] = Field(default="hop.plan/v2", alias="schema")
    plan_id: ReferenceId
    design_id: str = Field(pattern=r"^[a-z0-9][a-z0-9._-]{0,63}$")
    spec_digest: str = Field(pattern=r"^sha256:[0-9a-f]{64}$")
    payload_sequence: str
    paired_payload_sequence: str
    source_oligo: SequenceRecord
    hairpin_encoding_insert: HairpinEncodingInsert
    processing_route: PlanProcessingRoute
    lock: CompilationLock

    @field_validator("payload_sequence", "paired_payload_sequence", mode="before")
    @classmethod
    def normalize_payload_sequence(cls, value: object) -> str:
        if not isinstance(value, str):
            raise SequenceValidationError("DNA sequence must be a string.")
        return normalize_dna_sequence(value, allow_degenerate=True)

    @model_validator(mode="after")
    def validate_derivations(self) -> HopPlan:
        if self.paired_payload_sequence != reverse_complement_iupac(self.payload_sequence):
            raise ValueError("Paired payload sequence must be derived from the authored payload.")
        if self.processing_route.route_id != self.lock.processing_route_ref:
            raise ValueError("Resolved processing route and lock record disagree.")

        encoding = self.hairpin_encoding_insert
        actual_roles = tuple(feature.role for feature in encoding.features)
        expected_roles: tuple[FeatureRole, ...]
        if self.processing_route.kind == "direct_synthesis":
            if self.source_oligo.sequence != encoding.sequence:
                raise ValueError(
                    "Direct or component assembly requires source oligo and hairpin "
                    "encoding equality."
                )
            expected_roles = (
                FeatureRole.BASAL_LEFT_ARM,
                FeatureRole.PAYLOAD,
                FeatureRole.FOLDBACK_JUNCTION,
                FeatureRole.PAIRED_PAYLOAD,
                FeatureRole.BASAL_RIGHT_ARM,
            )
            if actual_roles != expected_roles:
                raise ValueError(
                    "Hairpin-encoding features must use the declared generic-route order."
                )
            foldback_sequence = self.processing_route.foldback_junction.sequence
            basal_left_arm = self.processing_route.basal_junction.left_arm
            basal_right_arm = self.processing_route.basal_junction.right_arm
            foldback_ref = self.processing_route.foldback_junction.junction_id
            basal_ref = self.processing_route.basal_junction.junction_id
        elif self.processing_route.kind == "component_assembly":
            if self.source_oligo.sequence != encoding.sequence:
                raise ValueError(
                    "Direct or component assembly requires source oligo and hairpin "
                    "encoding equality."
                )
            expected_roles = _feature_roles(
                has_stem_extension=self.processing_route.stem_extension is not None
            )
            if actual_roles != expected_roles:
                raise ValueError(
                    "Hairpin-encoding features must use the declared generic-route order."
                )
            foldback_sequence = self.processing_route.foldback.junction.sequence
            basal_left_arm = self.processing_route.basal.junction.left_arm
            basal_right_arm = self.processing_route.basal.junction.right_arm
            foldback_ref = self.processing_route.foldback.junction.junction_id
            basal_ref = self.processing_route.basal.junction.junction_id
        else:
            expected_source = (
                self.processing_route.foldback.precursor_sequence
                if self.processing_route.released_state is None
                else self.processing_route.released_state.precursor_top_strand
            )
            if self.source_oligo.sequence != expected_source:
                raise ValueError("Resolved-event source oligo must equal the actual route input.")
            expected_roles = _feature_roles(
                has_stem_extension=self.processing_route.stem_extension is not None
            )
            if actual_roles != expected_roles:
                raise ValueError(
                    "Resolved-event hairpin-encoding features must contain each physical role once "
                    "in the declared assembly order."
                )
            foldback_sequence = self.processing_route.foldback.junction.sequence
            basal_left_arm = self.processing_route.basal.junction.left_arm
            basal_right_arm = self.processing_route.basal.junction.right_arm
            foldback_ref = self.processing_route.foldback.junction.junction_id
            basal_ref = self.processing_route.basal.junction.junction_id
        if self.processing_route.catalog_ref != self.lock.catalog_ref:
            raise ValueError("Resolved catalog and lock record disagree.")
        if foldback_ref != self.lock.foldback_junction_ref:
            raise ValueError("Resolved foldback and lock record disagree.")
        if basal_ref != self.lock.basal_junction_ref:
            raise ValueError("Resolved basal and lock record disagree.")
        feature_by_role = {feature.role: feature for feature in encoding.features}
        if feature_by_role[FeatureRole.PAYLOAD].sequence != self.payload_sequence:
            raise ValueError("Payload feature must equal the authored payload sequence.")
        if feature_by_role[FeatureRole.PAIRED_PAYLOAD].sequence != self.paired_payload_sequence:
            raise ValueError("Paired-payload feature must equal the derived paired sequence.")
        if feature_by_role[FeatureRole.FOLDBACK_JUNCTION].sequence != foldback_sequence:
            raise ValueError("Foldback-junction feature must equal the resolved foldback junction.")
        if feature_by_role[FeatureRole.BASAL_LEFT_ARM].sequence != basal_left_arm:
            raise ValueError("Basal-left feature must equal the resolved basal junction.")
        if feature_by_role[FeatureRole.BASAL_RIGHT_ARM].sequence != basal_right_arm:
            raise ValueError("Basal-right feature must equal the resolved basal junction.")
        stem_extension = (
            None
            if self.processing_route.kind == "direct_synthesis"
            else self.processing_route.stem_extension
        )
        if stem_extension is not None and (
            feature_by_role[FeatureRole.STEM_EXTENSION_LEFT_ARM].sequence != stem_extension.left_arm
            or feature_by_role[FeatureRole.STEM_EXTENSION_RIGHT_ARM].sequence
            != stem_extension.right_arm
        ):
            raise ValueError("Stem-extension features must equal the resolved literal arms.")
        return self


def _feature_roles(*, has_stem_extension: bool) -> tuple[FeatureRole, ...]:
    if not has_stem_extension:
        return (
            FeatureRole.BASAL_LEFT_ARM,
            FeatureRole.PAYLOAD,
            FeatureRole.FOLDBACK_JUNCTION,
            FeatureRole.PAIRED_PAYLOAD,
            FeatureRole.BASAL_RIGHT_ARM,
        )
    return (
        FeatureRole.BASAL_LEFT_ARM,
        FeatureRole.STEM_EXTENSION_LEFT_ARM,
        FeatureRole.PAYLOAD,
        FeatureRole.FOLDBACK_JUNCTION,
        FeatureRole.PAIRED_PAYLOAD,
        FeatureRole.STEM_EXTENSION_RIGHT_ARM,
        FeatureRole.BASAL_RIGHT_ARM,
    )
