"""Public bounded-discovery facade for HOP Design."""

from hop_design.design.basal_candidates import search_basal_candidates
from hop_design.design.basal_processing import search_basal_processing_geometries
from hop_design.design.candidates import search_foldback_precursors
from hop_design.design.discovery import search_nicking_placements
from hop_design.design.foldback import search_foldback_arms
from hop_design.design.junction_routes import (
    search_basal_processing_routes,
    search_hairpin_junction_routes,
)
from hop_design.design.released_foldback import (
    search_released_foldback_geometries,
    search_released_foldback_precursors,
)
from hop_design.kernel.site_scanning import (
    classify_motif_presence,
    scan_nicking_agent,
    scan_release_agent,
)
from hop_design.models.catalog import (
    MotifPresenceReport,
    ResolvedNickSite,
    ResolvedReleaseSite,
)
from hop_design.models.discovery import (
    AdditionalNickConstraint,
    BasalCandidate,
    BasalCandidateExclusionStatus,
    BasalCandidateExclusionSummary,
    BasalCandidateSearchLimits,
    BasalCandidateSearchRequest,
    BasalCandidateSearchResult,
    BasalProcessingGeometryRequest,
    BasalProcessingGeometrySearchLimits,
    BasalProcessingGeometrySearchResult,
    BasalProcessingRouteSearchLimits,
    BasalProcessingRouteSearchResult,
    CandidateRejectionCode,
    CandidateRejectionSummary,
    CandidateSearchStatus,
    CandidateSearchTruncation,
    FoldbackPairingDomain,
    FoldbackPrecursorCandidate,
    FoldbackPrecursorSearchLimits,
    FoldbackPrecursorSearchRequest,
    FoldbackPrecursorSearchResult,
    HairpinJunctionRouteCandidate,
    HairpinJunctionRouteSearchLimits,
    HairpinJunctionRouteSearchResult,
    NickingPlacementBlocker,
    NickingPlacementFeasibility,
    NickingPlacementHit,
    NickingPlacementSearchLimits,
    NickingPlacementSearchResult,
    NickingPlacementTarget,
    NickingPlacementTruncation,
    ReleasedFoldbackBaseDomain,
    ReleasedFoldbackGeometryHit,
    ReleasedFoldbackGeometryRequest,
    ReleasedFoldbackGeometrySearchLimits,
    ReleasedFoldbackGeometrySearchResult,
    ReleasedFoldbackPrecursorBlocker,
    ReleasedFoldbackPrecursorCandidate,
    ReleasedFoldbackPrecursorSearchLimits,
    ReleasedFoldbackPrecursorSearchRequest,
    ReleasedFoldbackPrecursorSearchResult,
)
from hop_design.models.foldback import (
    FoldbackSearchLimits,
    FoldbackSearchRequest,
    FoldbackSearchResult,
)

__all__ = [
    "AdditionalNickConstraint",
    "BasalCandidate",
    "BasalCandidateExclusionStatus",
    "BasalCandidateExclusionSummary",
    "BasalCandidateSearchLimits",
    "BasalCandidateSearchRequest",
    "BasalCandidateSearchResult",
    "BasalProcessingGeometryRequest",
    "BasalProcessingGeometrySearchLimits",
    "BasalProcessingGeometrySearchResult",
    "BasalProcessingRouteSearchLimits",
    "BasalProcessingRouteSearchResult",
    "CandidateRejectionCode",
    "CandidateRejectionSummary",
    "CandidateSearchStatus",
    "CandidateSearchTruncation",
    "FoldbackPairingDomain",
    "FoldbackPrecursorCandidate",
    "FoldbackPrecursorSearchLimits",
    "FoldbackPrecursorSearchRequest",
    "FoldbackPrecursorSearchResult",
    "FoldbackSearchLimits",
    "FoldbackSearchRequest",
    "FoldbackSearchResult",
    "HairpinJunctionRouteCandidate",
    "HairpinJunctionRouteSearchLimits",
    "HairpinJunctionRouteSearchResult",
    "MotifPresenceReport",
    "NickingPlacementBlocker",
    "NickingPlacementFeasibility",
    "NickingPlacementHit",
    "NickingPlacementSearchLimits",
    "NickingPlacementSearchResult",
    "NickingPlacementTarget",
    "NickingPlacementTruncation",
    "ReleasedFoldbackBaseDomain",
    "ReleasedFoldbackGeometryHit",
    "ReleasedFoldbackGeometryRequest",
    "ReleasedFoldbackGeometrySearchLimits",
    "ReleasedFoldbackGeometrySearchResult",
    "ReleasedFoldbackPrecursorBlocker",
    "ReleasedFoldbackPrecursorCandidate",
    "ReleasedFoldbackPrecursorSearchLimits",
    "ReleasedFoldbackPrecursorSearchRequest",
    "ReleasedFoldbackPrecursorSearchResult",
    "ResolvedNickSite",
    "ResolvedReleaseSite",
    "classify_motif_presence",
    "scan_nicking_agent",
    "scan_release_agent",
    "search_basal_candidates",
    "search_basal_processing_geometries",
    "search_basal_processing_routes",
    "search_foldback_arms",
    "search_foldback_precursors",
    "search_hairpin_junction_routes",
    "search_nicking_placements",
    "search_released_foldback_geometries",
    "search_released_foldback_precursors",
]
